### ISSUE TITLE
The Low Balance of Decred Testnet Faucet&Asking for help for VSP

### ISSUE THREAD

**Issue by zihanzihan** [decred/testnetfaucet#69]
Hello everyone. 
I am a fan of cryptocurrency and want to learn it from testnet firstly. Recently. I uploaded my testnet wallet address to apply for some testnet DCR（https://faucet.decred.org/requestfaucet）. But the balance is so low (only 10.74) to get one ticket to  experience VSP.
So anyone can help to revise the code and improve the testnet DCR balance?
or anyone can let me be involved in your VSP of DCR to experience it.
I promise that i will send all my balance after VSP-test.
Thanks a lot for your generous help for the development of DCR,

**Comment by dajohi** [comment]
If you need testnet coins, ask on Matrix

**Comment by zihanzihan** [comment]
> If you need testnet coins, ask on Matrix

I am not sure about the Matrix meaning. Is a website or other APPs？Is this website (https://www.matrix.io/)?

**Comment by zihanzihan** [comment]
Oh I find how to join Matrix groupchat from official websit. And I will ask for help on it. Thanks a lot for your help @dajohi
